import json

seo_data = {
    "kimchi-jjigae": {
        "culturalContext": "Kimchi Jjigae is arguably the most beloved soul food in Korea. Historically born from the necessity to utilize over-fermented, sour kimchi, this stew has evolved into a daily staple in Korean households. It represents the quintessential taste of home, often cooked in a worn-out ddukbaegi (earthenware pot) and served boiling hot. It perfectly encapsulates the 'bap-doduk' (rice thief) concept, meaning it's so savory and deeply flavored that you'll end up eating multiple bowls of rice without realizing it. Every family has their own secret variation, with common additions being fatty pork belly, canned tuna, or mackerel.",
        "substituteExplanation": "Finding well-fermented, sour vegan or traditional kimchi abroad can be tricky, but the key to a great Kimchi Jjigae is the acidity and deep umami. If your local supermarket kimchi is too fresh, a splash of white vinegar or lemon juice mimics the fermented tang. Using chicken broth or vegetable bouillon instead of traditional anchovy-kelp broth provides the necessary savory backbone while being universally accessible. Ground pork or bacon can replace the specific cuts of Korean pork belly, rendering fat that fries the kimchi slightly before boiling—which is the ultimate secret to extracting its deep flavor."
    },
    "bulgogi": {
        "culturalContext": "Bulgogi, literally translating to 'fire meat,' is perhaps Korea's most famous culinary export. Tracing its roots back to the Goguryeo era (37 BC – 668 AD) as a skewered meat dish called 'Maekjeok,' it evolved into the thinly sliced, soy-marinated beef we know today. Traditionally considered a dish for royalty and special occasions due to the high cost of beef in agrarian Korea, it is now loved globally. Its perfect balance of savory, sweet, and garlicky flavors makes it universally appealing, often served sizzling on a gridiron or pan-fried with glass noodles and vegetables.",
        "substituteExplanation": "Authentic Bulgogi relies on Asian pear (Bae) in the marinade, which acts as a natural meat tenderizer and provides a delicate sweetness. If unavailable, an everyday Bosc pear, a sweet apple, or even a splash of pineapple juice mixed with brown sugar perfectly replicates this enzymatic tenderizing effect. Ribeye or sirloin are ideal, but any thinly sliced beef (even cheap cuts) will work when soaked in this powerful marinade. Replacing Korean soy sauce with standard Kikkoman or local generic soy sauce works flawlessly when balanced with standard sesame oil and abundant minced garlic."
    },
    "bibimbap": {
        "culturalContext": "Bibimbap ('mixed rice') is a beautiful visual representation of Korean culinary philosophy, balancing five traditional colors (Obangsaek) representing the five elements of the universe. Historically eaten on the eve of the Lunar New Year to clear out leftover side dishes before the new year began, it has become a global health food icon. Whether served in a hot stone bowl (Dolsot) that crisps the rice at the bottom or in a simple brass bowl, the act of vigorously mixing the ingredients with deep red Gochujang symbolizes harmony and unity.",
        "substituteExplanation": "This dish is highly adaptable. While authentic recipes call for specific Korean roots like bellflower (Doraji) or bracken fern (Gosari), the core identity of Bibimbap lies in the *method* rather than rigid ingredients. Any sautéed vegetables—zucchini, spinach, carrots, or even everyday bell peppers and kale—work perfectly. The secret weapon is the Gochujang (Korean chili paste) sauce. If you cannot find it, a mixture of Sriracha, miso paste (or soy sauce), and a touch of honey or sugar creates a remarkably similar sweet, savory, and spicy umami profile that ties the bowl together."
    },
    "yangnyeom-chicken": {
        "culturalContext": "Yangnyeom Chicken is the crown jewel of Korea's modern 'Chimaek' (Chicken and Beer) culture. Born in the late 1970s and 1980s when Western fried chicken was introduced to Korea, local chefs adapted it by tossing the incredibly crispy, double-fried pieces in a sticky, sweet, and spicy glaze. This innovation transformed fried chicken from a simple fast food into a deeply flavorful, communal dining experience, usually enjoyed late at night with friends, family, and cold draft beer. It is the ultimate comfort food for modern Koreans.",
        "substituteExplanation": "The signature crunch of Korean fried chicken comes from potato starch or a mix of fine cornstarch and baking powder, which resists getting soggy under the heavy sauce. You can easily replicate this at home without specialty frying mixes. The iconic sticky red sauce traditionally requires Korean strawberry jam, rice syrup (Mulyot), and Gochujang. A brilliant supermarket hack uses standard ketchup, local honey or corn syrup, and crushed red pepper flakes mixed with garlic. The ketchup provides the necessary tang and color, while honey gives it that glorious, irresistible sticky sheen."
    },
    "japchae": {
        "culturalContext": "Japchae is Korea's quintessential festive dish, mandatory at weddings, birthdays, and major holidays like Chuseok (Harvest Festival) and Seollal (Lunar New Year). Originally invented in the 17th century for King Gwanghaegun without any noodles (just vegetables), the dish transformed in the 20th century with the mass production of sweet potato starch noodles (Dangmyeon). The glass-like, chewy noodles absorb the rich soy-sesame flavor, while the individually stir-fried vegetables maintain their distinct textures and vibrant colors, representing prosperity and longevity.",
        "substituteExplanation": "While authentic sweet potato glass noodles (Dangmyeon) have a unique chewy bite, they can be hard to find. Regular vermicelli, rice noodles, or even angel hair pasta can deliver a satisfying alternative when tossed in the signature sauce. The flavor profile relies heavily on toasted sesame oil and dark soy sauce. If you lack Korean soy sauce, mixing standard light soy sauce with a tiny dash of molasses or dark brown sugar mimics the deep color and rich, slightly sweet caramel notes required for a perfect homemade Japchae."
    },
    "dakbokkeumtang": {
        "culturalContext": "Dakbokkeumtang (Spicy Braised Chicken) is a rustic, hearty, and intensely flavorful Korean comfort dish. Known historically as 'Dakdoritang,' this dish simmers bone-in chicken chunks, large wedges of potato, and carrots in a fiery, sweet, and savory red broth. It is the perfect winter warmer and a favorite item at casual Korean taverns (Pojangmacha) to accompany Soju. The potatoes break down slightly during the long braise, naturally thickening the brilliant red broth, which is religiously spooned over bowls of steaming white rice.",
        "substituteExplanation": "The vibrant red color and spicy kick traditionally come from Gochugaru (Korean chili flakes) and Gochujang. If local stores don't stock these, paprika mixed with a pinch of cayenne pepper delivers the color and heat, while a spoonful of tomato paste mixed with soy sauce and sugar perfectly replaces the thick, umami-rich body of Gochujang. Using everyday bone-in chicken thighs and standard russet potatoes ensures the broth develops that rich, sticky consistency that defines the dish, without needing a single trip to a specialty Asian market."
    },
    "chadol-doenjang-jjigae": {
        "culturalContext": "Doenjang Jjigae (Soybean Paste Stew) is to Koreans what chicken noodle soup is to Americans—the ultimate, everyday comforting meal. While standard Doenjang Jjigae is humble and vegetable-forward, the addition of 'Chadolbaegi' (thinly sliced beef brisket) elevates it into a rich, luxurious dish often served at premium Korean BBQ restaurants. The rich fat from the brisket melts into the earthy, deeply savory fermented soybean broth, creating an incredibly satisfying synergy that is intoxicatingly delicious when mixed with rice.",
        "substituteExplanation": "Authentic Doenjang (Korean soybean paste) has a distinct, pungent earthiness. The best accessible substitute is Japanese Miso paste, which is milder. By mixing Miso with a splash of soy sauce and a tiny bit of extremely finely minced garlic, you replicate the sharp, fermented depth of Doenjang. Finding Chadolbaegi (shaved brisket) can be tough; instead, use any fatty, thinly sliced beef like Philly cheesesteak meat, or simply fry up some fatty bacon or pancetta first to create the rich, fatty base before adding the broth and vegetables."
    },
    "gochujang-samgyeopsal": {
        "culturalContext": "Samgyeopsal (pork belly) is the undisputed king of Korean BBQ. While usually grilled plain and dipped in salt, Gochujang Samgyeopsal involves marinating the thick slices of pork belly in a spicy, sweet red pepper paste before grilling. The sugars in the marinade caramelize and char beautifully over the fire, creating a smoky, spicy crust that contrasts with the rich, melting pork fat. It's a favorite for casual dining, usually wrapped in fresh lettuce leaves with garlic (Ssam) and washed down with cold Soju.",
        "substituteExplanation": "The marinade requires Gochujang, but a mix of Sriracha, soy sauce, a spoonful of brown sugar, and a dash of ketchup perfectly mimics its spicy, sweet, and thick properties. Pork belly is essential, but if thick slabs are unavailable, thick-cut streaky bacon (unsmoked if possible) or fatty pork shoulder chops work wonderfully. The key is in the aggressive caramelization—letting the sugar in the substitute marinade slightly char in the pan gives you that authentic, smoky Korean BBQ flavor right from your standard kitchen stovetop."
    },
    "kkanpunggi": {
        "culturalContext": "Kkanpunggi is a beloved Korean-Chinese dish, created by early Chinese immigrants in Korea who adapted their traditional recipes to suit Korean palates, which favored spicy, sweet, and garlicky flavors. It consists of bite-sized pieces of deep-fried chicken glazed in a sweet, sour, and spicy soy-based sauce infused with leeks, garlic, and dried red chilies. Unlike standard sweet and sour pork (Tangsuyuk), Kkanpunggi's sauce is completely absorbed into the crispy batter, delivering an explosive punch of flavor in every single bite.",
        "substituteExplanation": "The core of this dish is the aromatic chili oil and the sticky glaze. You don't need Korean specific dried peppers; any dried red chilies (like Arbol) or standard red pepper flakes fried briefly in oil will release the smoky heat required. The batter traditionally uses potato starch for crispiness, but an everyday mix of all-purpose flour and cornstarch yields an excellent, robust crunch. A simple sauce made of local supermarket soy sauce, white vinegar, and sugar flawlessly captures the iconic sweet-and-sour tang that defines classic Kkanpunggi."
    },
    "galbi-jjim": {
        "culturalContext": "Galbi-jjim (Braised Beef Short Ribs) is the ultimate dish of luxury and celebration in Korean cuisine. Historically reserved for royalty due to the exorbitant cost of beef ribs, it remains the centerpiece of holiday feasts like Chuseok, birthdays, and Lunar New Year. The ribs are slow-cooked for hours in a rich, sweet, and savory soy sauce marinade with chestnuts, dates, and root vegetables until the meat is literally falling off the bone. The remaining dark, syrupy sauce is considered liquid gold, perfect for mixing with rice.",
        "substituteExplanation": "Traditional Galbi-jjim uses specific Korean-cut short ribs, but standard English-cut short ribs, beef chuck roast, or even pork shoulder will braise down into the exact same melt-in-your-mouth texture. The quintessential sweet marinade relies on Asian pear and rice syrup. A brilliant local alternative is using a blended sweet apple or regular pear, combined with brown sugar and corn syrup. This mimics the enzyme-tenderizing effect and provides the rich, deep caramel color and glossy finish that makes the dish look and taste incredibly luxurious."
    },
    "jeyuk-bokkeum": {
        "culturalContext": "Jeyuk Bokkeum (Spicy Stir-fried Pork) is the backbone of the Korean worker's lunch. It is a staple at 'Gisashikdang' (drivers' diners) due to its fast preparation, cheap ingredients, and robust, spicy-sweet flavor that pairs perfectly with large bowls of rice. Thinly sliced pork is marinated in a vibrant red Gochujang sauce and stir-fried over high heat to achieve a smoky 'fire taste' (Bulmat). It's the ultimate everyday comfort food, simple, aggressively flavorful, and deeply satisfying.",
        "substituteExplanation": "While authentic recipes demand Gochujang (Korean chili paste) and Gochugaru (Korean chili flakes), you can hack the flavor profile by combining Sriracha (for the garlic/chili kick), tomato paste (for the savory, thick body), soy sauce, and a generous amount of local honey or sugar. Standard thinly sliced pork shoulder or even cheap pork chops cut into thin strips work perfectly. The secret to the authentic taste isn't just the paste, but high-heat frying to slightly caramelize the sugars in the meats, achievable on any Western stove."
    },
    "samgyetang": {
        "culturalContext": "Samgyetang (Ginseng Chicken Soup) is Korea's iconic summer endurance food. Ironically eaten on the three hottest days of the year (Boknal), it follows the traditional philosophy of 'Yi Yeol Chi Yeol' (fighting heat with heat). A whole young chicken is stuffed with sticky rice, garlic, jujubes, and a whole ginseng root, then boiled until the broth turns milky and profoundly aromatic. It is believed to restore stamina and internal energy lost to the summer heat, offering an incredibly clean, herbal, and nourishing flavor profile.",
        "substituteExplanation": "Finding fresh ginseng roots and Korean jujubes outside of specialty markets is tough. However, the soul of Samgyetang is its deep, clean, garlic-infused chicken broth. You can substitute the herbal notes by using a few slices of fresh ginger and a generous amount of whole garlic cloves inside any small local Cornish hen or roasting chicken. Standard short-grain rice or arborio rice (used for risotto) works perfectly as a substitute for Korean sweet rice, absorbing the rich chicken stock wonderfully while it quietly simmers."
    },
    "dakgomtang": {
        "culturalContext": "Dakgomtang is a humble, deeply comforting Korean chicken bone soup. Unlike the heavy, herbal Samgyetang, Dakgomtang focuses purely on the unadulterated, clean essence of slow-boiled chicken. Once the broth is milky white and rich, the chicken meat is shredded by hand, lightly seasoned with salt, garlic, and sesame oil, and added back to the hot broth with abundant chopped scallions. It is a classic restorative meal, famous for curing hangovers and cold weather chills with its simple, incredibly savory depth.",
        "substituteExplanation": "This recipe requires almost zero specialty Korean ingredients, making it the perfect entry-level authentic recipe. You only need a whole roasting chicken, garlic, onions, and black pepper. The secret to the authentic Korean taste is not the ingredients, but the technique: aggressively boiling the bones to emulsify the fat into the water, creating a milky, opaque broth. Tearing the meat by hand, rather than cutting it, and massaging it with standard supermarket sesame oil and salt before serving provides the distinctly Korean culinary texture."
    },
    "garlic-pickle": {
        "culturalContext": "Maneul Jangajji (Pickled Garlic) is a timeless Korean side dish (Banchan) that transforms pungent raw garlic into sweet, salty, and incredibly crisp nuggets. Made by aging whole garlic cloves in a brine of soy sauce, vinegar, and sugar, the harsh allicin mellows out entirely over several weeks, leaving a deeply savory, umami-packed pickle. It is an essential palate cleanser at Korean BBQ restaurants, incredibly healthy, and traditionally prepared in large jars to last throughout the lean winter months.",
        "substituteExplanation": "This recipe is universally accessible as it uses purely standard pantry ingredients. Any local supermarket garlic, white vinegar, standard soy sauce, and white sugar will produce a perfectly authentic result. The key to the Korean flavor profile is the exact ratio of the brine (often 1:1:1 of soy sauce, vinegar, and sugar, adjusted to taste) and the patience to let it ferment in the refrigerator. No specialty Asian markets are needed to create this incredibly complex, crunchy, and addictive side dish."
    },
     "jang-susam": {
        "culturalContext": "Jang Susam (Braised Fresh Ginseng) is an aristocratic side dish, deeply tied to traditional Korean medicine (Hanbang). Ginseng is revered in Korea as a cure-all root, providing intense vitality. By gently braising fresh, bitter ginseng roots in a sweet and salty soy sauce glaze, the harsh medicinal bitterness transforms into an elegant, earthy sweetness. Historically served only to elders and royalty to boost their health, it is a luxurious, caramelized banchan that showcases the sophisticated side of Korean culinary arts.",
        "substituteExplanation": "Fresh ginseng (Susam) is notoriously difficult to find globally. While the medicinal properties are unique, the elegant braising technique can be heavily applied to locally available root vegetables like parsnips, young burdock root, or even thick-cut carrots. Simmering these roots in a standard mix of local soy sauce, honey (or maple syrup), and a dash of sesame oil until they are coated in a sticky, glossy, dark glaze perfectly replicates the luxurious, earthy, sweet-and-salty profile of traditional Korean royal court banchans."
    },
    "aukguk": {
        "culturalContext": "Auk-guk (Mallow Soup) is a deeply nostalgic, countryside Korean soup. Mallow (Auk) is a leafy green that becomes uniquely slippery and soft when bruised and boiled. The soup is traditionally made by vigorously rubbing the leaves to remove their bitter green slime, then boiling them in a rich, earthy broth made from fermented soybean paste (Doenjang) and dried anchovies. It is commonly described as the taste of a Korean grandmother's kitchen—unpretentious, incredibly soothing, and intimately tied to the local earth.",
        "substituteExplanation": "Mallow (Auk) is rarely found in Western supermarkets, but Swiss chard or spinach act as brilliant substitutes, offering a very similar soft, leafy texture when boiled. Traditional Doenjang (soybean paste) can be replaced with accessible Japanese Miso paste. While Miso is less pungent, boiling it slightly longer with a few dried mushrooms or vegetable stock instead of the traditional dried anchovies provides the identical earthy, savory, and comforting umami depth that defines this classic Korean countryside soup."
    },
    "oyster-soft-tofu-stew": {
        "culturalContext": "Gul Sundubu Jjigae (Oyster Soft Tofu Stew) is a luxurious winter variation of the classic spicy Korean tofu stew. Fresh oysters add an incredibly briny, oceanic depth to the fiery, chili-infused broth. Served in a boiling hot stone pot, a raw egg is cracked into the bubbling red stew right at the table. It is famous in coastal Korean cities as a premium, protein-packed comfort food that warms the body and serves as an elite hangover cure (Haejang-guk) due to the amino acids in the oysters.",
        "substituteExplanation": "While authentic recipes call for Korean chili oil and Gochugaru, you can easily replicate the spicy base by frying local supermarket chili flakes and crushed garlic in neutral oil to release the red color and smoky flavor. Standard silken or soft tofu found in the health food aisle works perfectly. Using a simple chicken or vegetable bouillon cube mixed with the natural juices from a jar of fresh local oysters creates a surprisingly profound and authentic oceanic broth without needing specialized Korean anchovy-kelp packets."
    },
    "spicy-chili-steamed": {
        "culturalContext": "Kkari-gochu Jjim (Steamed Shishito Peppers) is a classic 'Mom's recipe' (Eomma-sonmat) side dish. Wrinkled mild chilies (Kkari-gochu) are tossed in flour, steamed just until tender but still snappy, and then dressed in a pungent, salty, and garlicky soy sauce mixture. The flour coating turns slightly gummy and absorbs the savory dressing perfectly. It is a staple summer banchan in Korea, representing the ingenious traditional methods of utilizing abundant seasonal vegetables and turning them into complex, rice-stealing flavors.",
        "substituteExplanation": "Korean wrinkled chilies (Kkari-gochu) can be directly swapped with Shishito peppers or Padron peppers, which are increasingly common in Western supermarkets. The technique requires absolutely no specialty ingredients: plain all-purpose flour for the steaming coat, and a dressing made of standard soy sauce, a pinch of sugar, minced local garlic, and sesame oil. This brilliant, simple steaming hack instantly transports the flavor profile of a traditional Korean countryside kitchen onto any global dining table."
    },
    "oyster-soup-rice": {
        "culturalContext": "Gul Gukbap (Oyster Soup with Rice) is a celebrated regional dish from the coastal city of Tongyeong. It is the epitome of clean, pure Korean flavors. Plump, fresh oysters are briefly boiled with radish and seaweed in a clear broth, then served ceremoniously with rice submerged directly in the soup. Extremely light, non-spicy, and profoundly briny, it is revered as a premium restorative meal in the winter months, maximizing the natural, milky flavor of the 'milk of the sea' without masking it with heavy spices.",
        "substituteExplanation": "This delicate soup relies purely on the freshness of the ingredients rather than complex specialty sauces. A standard Western fish stock, or even water boiled with a handful of accessible dried seaweed (like kombu or wakame) and daikon radish (or standard white turnips), serves as the perfect base. Adding fresh, locally sourced jarred oysters and a splash of standard soy sauce and sesame oil right at the end flawlessly mimics the clean, elegant, oceanic flavor of an authentic Korean coastal restaurant."
    },
    "pork-backbone-stew": {
         "culturalContext": "Gamjatang (Pork Bone Stew) is a legendary Korean late-night food. Massive pork neck and backbones are slowly boiled until the meat softly falls off. The deeply complex, spicy, and earthy broth is thickened naturally by the marrow and potatoes (Gamja), heavily seasoned with perilla seed powder (Deulkkae). It is a communal dish, usually shared over a portable gas stove in the center of the table with copious amounts of Soju, beloved for its messy, hands-on eating experience and intensely hearty flavor.",
        "substituteExplanation": "Pork neck bones can often be sourced cheaply from local butchers if unavailable in standard aisles. The signature earthy thickness of Gamjatang comes from perilla seed powder, which is hard to find. However, blending toasted sesame seeds into a fine powder provides a remarkably similar nutty, milky richness to the broth. For the spicy base, a mixture of Sriracha, miso paste, and a dash of local mustard mimics the complex, funky, and spicy depth of the traditional Gochujang and Doenjang mix used in Korea."
    },
    "kimchi-bokkeumbap": {
         "culturalContext": "Kimchi Bokkeumbap (Kimchi Fried Rice) is the ultimate Korean survival food and a favorite among students and busy parents alike. Born out of the necessity to use up deeply fermented, pungent, older kimchi, frying it mellows the extreme sourness and caramelizes its flavors into a deeply savory, slightly spicy base. It is almost always crowned with a sunny-side-up fried egg and a sprinkle of roasted seaweed, making it a simple, iconic, and universally loved dish that perfectly balances fat, acid, and heat.",
        "substituteExplanation": "The secret to great Kimchi Fried Rice isn't specialty ingredients, but using highly acidic, aged kimchi. If your local store-bought kimchi is too fresh and sweet, splash a teaspoon of white vinegar into the pan while frying it. Furthermore, you don't need Korean spam or specific meats; local bacon, diced sausage, or even canned tuna adds the crucial fat needed to fry the kimchi correctly. A dash of standard soy sauce and a drizzle of common sesame oil is all you need to finish this globally accessible masterpiece."
    },
    "gungmul-tteokbokki": {
         "culturalContext": "Gungmul Tteokbokki (Soupy Spicy Rice Cakes) is a nostalgic variation of Korea's most iconic street food. Unlike the thick, sticky glaze of standard Tteokbokki, this version is served in an abundant, fiery, and sweet red broth. It gained massive popularity outside schools in the 80s and 90s because the extra soup was perfect for dipping deep-fried snacks (Twigim), boiled eggs, and kimbap. Eating it is a tactile, comforting experience that instantly transports Koreans back to their childhoods.",
        "substituteExplanation": "While authentic cylindrical rice cakes (Garaetteok) provide the best chew, you can use any accessible rice cakes, or even substitute with thick, chewy pasta shapes like gnocchi in a pinch. The fiery soup base relies heavily on Gochujang (Korean chili paste). If unavailable, whisking together tomato paste, Sriracha, soy sauce, and a generous amount of local sugar or corn syrup recreates the exact glossy, spicy-sweet broth. Adding local fish sticks or fish balls perfectly replaces the traditional Korean fish cakes (Eomuk)."
    },
    "dubu-jorim": {
         "culturalContext": "Dubu-jorim (Spicy Braised Tofu) is an incredibly common, beloved everyday side dish (Banchan) in the Korean home. Thick slices of firm tofu are pan-fried until a golden crust develops, then briefly simmered in a salty, spicy, and slightly sweet soy sauce mixture studded with garlic and scallions. The crust acts like a sponge, absorbing the fiery, savory sauce. It transforms plain, bland tofu into a robust, meaty, and intensely flavorful protein that pairs flawlessly with a bowl of plain white rice.",
        "substituteExplanation": "This recipe perfectly adapts to any global kitchen. Extra-firm tofu from any local grocery store is essential. The authentic Korean braising sauce (Gochugaru and soy sauce) can be easily hacked by mixing standard light soy sauce with a pinch of cayenne pepper, a dash of paprika for the red hue, sugar, and abundant minced local garlic. The key to the authentic Korean texture is ensuring you aggressively pan-fry the tofu in standard cooking oil until it develops a tough golden skin *before* adding the sauce."
    },
     "algamja-jorim": {
         "culturalContext": "Algamja-jorim (Braised Baby Potatoes) is a delightful, universally appealing Korean side dish. Whole, unpeeled baby potatoes are slowly braised in a dark, sweet, and sticky soy sauce reduction until they wrinkle and develop a glossy caramel coating. The contrast between the chewy, intensely savory-sweet skin and the soft, fluffy interior is addictive. It is a favorite among Korean children and a staple in lunchboxes (Dosirak), symbolizing the Korean knack for elevating humble, cheap root vegetables into culinary art.",
        "substituteExplanation": "No specialty Korean ingredients are required. Any local baby potatoes or fingerling potatoes work perfectly. The essential, sticky 'candy-like' coating is traditionally achieved with Korean rice syrup (Mulyot). You can flawlessly replicate this glossy finish by using dark corn syrup, maple syrup, or even local honey mixed with standard soy sauce. The authentic technique simply involves patience: letting the water evaporate entirely so the sugars in the syrup and soy sauce locally caramelize and blister the skins in the pan."
    },
    "cheonggukjang-jjigae": {
         "culturalContext": "Cheonggukjang-jjigae (Rich Soybean Paste Stew) is the ultimate 'acquired taste' of Korean cuisine, notorious for its intensely pungent, fermented aroma—often compared to strong blue cheese. Unlike Doenjang, Cheonggukjang is fermented rapidly over a few days, retaining whole, incredibly savory soybeans. Despite its strong smell, the taste is profoundly nutty, earthy, and deeply comforting. It is a traditional winter staple in rustic Korean homes, loaded with tofu, radish, and pork, acting as a powerful, probiotic-rich soul food.",
        "substituteExplanation": "Authentic Cheonggukjang paste is almost impossible to find in standard Western supermarkets due to its extreme fermentation. However, you can mimic its deep, funky, and nutty flavor profile by combining Japanese 'Natto' (fermented soybeans, often found in the sushi/frozen section) with standard Miso paste and a splash of soy sauce. Smashing half of the Natto beans into the Miso broth provides that identical thick, rustic texture and the profoundly earthy, complex umami bomb that defines this hardcore traditional stew."
    },
    "gochu-basasak-chicken": {
         "culturalContext": "Gochu Basasak (Crispy Pepper Chicken) represents the modern evolution of Korea's hyper-competitive fried chicken delivery market. Unlike traditional thick-battered, deep-fried chicken, 'Basasak' style is oven-roasted or air-fried with an incredibly thin, exceptionally crispy, zero-grease skin. The magic is in the marinade: it is heavily infused with mild green chilies. It delivers a clean, addictive, and slightly spicy vegetal kick that cuts through the richness of the meat, making it a massive modern hit among young Koreans.",
        "substituteExplanation": "The secret to 'Basasak' (meaning 'crunchy') without deep frying is thoroughly drying the chicken skin and coating it very lightly with baking powder and local cornstarch before air-frying or baking. For the iconic green chili flavor, blending fresh jalapeños or serrano peppers into a liquid and marinating the chicken in it overnight perfectly infuses the meat with the authentic Korean 'Gochu' taste. Baking it at a high temperature guarantees that shattering, grease-free crunch that rivals the best Seoul delivery spots."
    },
    "gimbap": {
         "culturalContext": "Gimbap (Seaweed Rice Rolls) is the quintessential Korean picnic and travel food. Unlike Japanese sushi, the rice in Gimbap is seasoned with nutty sesame oil and salt, not vinegar, and it never contains raw fish. Instead, it is tightly packed with colorful, cooked ingredients representing harmony: yellow pickled radish, orange carrots, green spinach, and brown bulgogi or egg. It is deeply nostalgic, representing childhood school field trips (Sopoong) and the loving care of mothers who wake up at dawn to roll them.",
        "substituteExplanation": "Gimbap is infinitely customizable based on your local supermarket. Dried seaweed sheets (Nori) are now globally available. If you cannot find yellow pickled radish (Danmuji), standard dill pickles, pickled jalapeños, or even crisp cucumbers provide the necessary crunchy, acidic contrast. Instead of specific Korean beef bulgogi, you can use canned tuna mixed with local mayonnaise, cooked hot dogs, or ham. The only non-negotiable hack for authenticity is generously rubbing the finished roll with toasted sesame oil before slicing."
    },
    "haemul-pajeon": {
         "culturalContext": "Haemul Pajeon (Seafood Green Onion Pancake) is inextricably linked to raining days in Korea. There is a deeply ingrained cultural association between the sound of rain hitting the roof and the sound of batter sizzling in a hot pan. Packed with an abundance of sharp green onions (Pa) and assorted seafood (Haemul), the pancake is fried until golden and shatteringly crisp on the outside, while remaining slightly chewy on the inside. It is communally shared and religiously paired with Makgeolli (Korean rice wine).",
        "substituteExplanation": "Authentic Korean pancake mix (Buchimgae-garu) is pre-seasoned, but you can build a better, crispier batter using a 50/50 mix of all-purpose flour and cornstarch from your local store, seasoned with a dash of garlic powder and salt. The key is ice-cold water for the batter. You don't need a specific Korean seafood mix; frozen local shrimp, squid rings, or even canned clams work beautifully. The authentic flavor comes from using copious amounts of standard local green onions and frying in abundant neutral oil."
    },
    "sundubu-jjigae-classic": {
         "culturalContext": "Sundubu Jjigae (Soft Tofu Stew) is a vibrant, bubbling masterpiece of Korean casual dining. Utilizing uncurdled, extra-soft tofu (Sundubu), the stew relies on a base of incredibly flavorful, spicy chili oil infused with garlic and pork or seafood. Served furiously boiling in an earthenware pot, it has become wildly popular globally due to its intense, savory-spicy broth that contrasts perfectly with the clouds of silky, mild tofu. It is the ultimate comfort food for freezing winter days.",
        "substituteExplanation": "The foundation of this stew is 'Dadaegi' (spicy paste). If Gochugaru (Korean chili flakes) isn't available, blending standard red pepper flakes with a tiny bit of smoked paprika and frying it slowly in oil with minced local garlic and onion creates a remarkably similar, flavor-packed chili oil base. Standard silken tofu in tubes or boxes from the health-food aisle is identical to Korean Sundubu. Adding a splash of soy sauce and local chicken broth completes the deep, authentic, umami-rich soup profile."
    },
    "samgyeopsal": {
         "culturalContext": "Samgyeopsal (Pork Belly) grilling is arguably the most authentic, communal Korean dining experience. Slices of rich, fatty, unmarinated pork belly are grilled at the table. It's not just a meal; it's a social ritual of wrapping the sizzling meat in fresh lettuce with garlic and spicy ssamjang (wrap sauce), clinking shot glasses of Soju, and sharing stories. The meat's purity relies entirely on its quality and the fun, interactive, loud, and incredibly savory experience of building your own perfect bite.",
        "substituteExplanation": "Authentic Samgyeopsal requires no marinades, making it purely about sourcing. Any local butcher's thick-cut, unsmoked bacon or fresh pork belly slices will perfectly replicate the meat. The crucial authentic element is the 'Ssamjang' dipping sauce. If you cannot buy it, mixing equal parts of Japanese Miso paste with Sriracha, a dash of local honey, minced garlic, and sesame oil creates a shockingly accurate, deeply savory, and sweet-spicy dipping paste that brings the authentic Seoul BBQ experience to your home kitchen."
    },
    "kkaennip-jangajji": {
         "culturalContext": "Kkaennip Jangajji (Pickled Perilla Leaves) is a beloved, sharp, and aromatic side dish famously known as a 'rice thief' (Bap-doduk). Perilla leaves have a unique, minty-licorice flavor that is uniquely Korean. Taking hundreds of these leaves and individually layering them with a spicy, salty, and sweet soy sauce brine is an act of deep culinary devotion. Once aged, you peel a single, paper-thin, intensely flavorful leaf to wrap around a spoonful of hot rice—an incredibly elegant and classic Korean bite.",
        "substituteExplanation": "Korean Perilla leaves (Kkaennip) possess a highly specific flavor that is hard to replace. However, large fresh basil leaves or even Swiss chard leaves can be used with the exact same Korean pickling technique. The magic lies in the marinade: a mixture of local soy sauce, sugar, minced garlic, and a pinch of chili flakes. Layering any local sturdy, aromatic green leaf in this authentic, balanced soy-brine will yield a deeply savory, complex, and crisp pickle that mimics this classic Korean preservation art perfectly."
    },
    "gochujang-yukhoe": {
         "culturalContext": "Yukhoe (Korean Steak Tartare) is a premium delicacy often served at high-end Korean BBQ restaurants or traditional wedding banquets. While standard Yukhoe is seasoned mildly with sesame oil and soy sauce to let the raw beef shine, the Gochujang (spicy) version originates from the Jeolla province, famous for its robust seasoning. The lean, raw beef is tossed in a sweet, garlicky, and fiery red chili paste, topped with a raw egg yolk and crisp Asian pear, creating a luxurious, melt-in-the-mouth textural masterpiece.",
        "substituteExplanation": "The most critical step is sourcing heavily vetted, extremely fresh, incredibly lean beef (like tenderloin or sirloin) from a trusted local butcher. The authentic Gochujang sauce can be replicated by vigorously whisking together Sriracha, a small dollop of tomato paste, soy sauce, abundant local honey, and toasted sesame oil. Slicing a crisp, sweet local apple (like Honeycrisp or Fuji) perfectly mimics the sweet, watery crunch of the traditional Asian pear, providing the essential textural contrast to the soft, spicy beef."
    },
    "nabak-kimchi": {
         "culturalContext": "Nabak Kimchi (Water Kimchi) is a light, incredibly refreshing, non-spicy variation of Kimchi characterized by its abundant, mildly tangy pink broth. Filled with thinly sliced radish and cabbage, it heavily features floating fruits like apple and pear. It is historically served in the spring and deeply associated with traditional Korean holidays to cut through the heavy, greasy festive foods. The naturally fermented, vitamin-rich cold broth is often drunk straight from the bowl like a savory, carbonated, fruity digestive tonic.",
        "substituteExplanation": "This is one of the easiest kimchis to make globally as it requires zero specialty chili powders or fish sauces. You simply need everyday radishes, local cabbage, a sweet apple, and coarse salt. The beautiful, authentic pink hue and subtle tang are achieved by blending a little local garlic, ginger, and onion with water, and letting the salted vegetables sit in this water at room temperature for two days. The natural lactic acid fermentation happens regardless of geography, producing a perfectly authentic, fizzy Korean water kimchi."
    },
    "minari-jangajji": {
         "culturalContext": "Minari Jangajji (Pickled Water Dropwort) captures the very essence of the Korean spring. Minari is a uniquely fragrant, slightly bitter, and crisp aquatic plant that features heavily in Korean culinary poetry and recent pop culture (like the Oscar-winning film). Pickling it in a sweet, sour, and salty soy brine tames its herbaceous bitterness while retaining its profound crunch. It is an exquisite, palate-cleansing side dish that pairs phenomenally well with heavy, fatty meats like grilled pork belly.",
        "substituteExplanation": "Authentic Minari has a distinctive peppery, celery-like flavor. The best Western supermarket substitute is watercress, celery leaves, or sturdy flat-leaf parsley. You can flawlessly recreate this elegant, traditional pickle by pouring a boiling hot mixture of equal parts local soy sauce, white vinegar, and white sugar directly over the fresh local greens. The boiling brine slightly wilts the greens while shocking them to preserve their bright green color and intense crunch, mirroring the authentic Korean countryside preservation technique."
    },
     "nurungji-baeksuk": {
         "culturalContext": "Nurungji Baeksuk (Whole Chicken Soup with Scorched Rice) is the ultimate rustic, hearty evolution of Korean medicinal chicken soup. While standard Baeksuk boils the chicken plain, this version adds a thick, chewy layer of 'Nurungji' (crispy scorched rice) to the boiling pot. The scorched rice slowly melts into the broth, infusing the clean chicken flavor with a profoundly deep, roasted, nutty aroma. It is a massive, communal comfort food, famous for being the ultimate, gut-warming meal after a long hike in the Korean mountains.",
        "substituteExplanation": "The secret ingredient is the scorched rice. You don't need a specialty Korean stone pot to make it. Simply press cooked standard short-grain or medium-grain local rice into a thin layer on a dry, non-stick frying pan over medium-low heat until it becomes a deeply golden, crispy, and hard cracker. Dropping this homemade 'cracker' into a pot where a standard local whole chicken has been boiling with garlic and onions flawlessly recreates the insanely comforting, roasted chicken porridge texture of authentic Baeksuk."
    },
    "jangdokdok-pork": {
        "culturalContext": "Jangdokdok-i (Soy-Braised Shredded Pork) is a historical, royal-court-inspired Korean dish. Its unique name comes from the 'dok-dok' sound made while rapidly chopping the meat into small, uniform strips. Unlike the fiery red pork dishes common today, this is simmered gently in a sweet and deeply savory soy sauce (Ganjang) reduction. It is a sophisticated, non-spicy, umami-rich dish traditionally reserved for the elderly and young children due to its extremely tender texture and mild, comforting flavor profile.",
        "substituteExplanation": "This elegant braise relies entirely on the technique rather than exotic ingredients. Using any lean, local cut of pork (like tenderloin or loin), cut it into matchsticks. The authentic Korean soy-marinade is perfectly replicated using standard supermarket soy sauce, a generous spoonful of local honey, minced garlic, and black pepper. The secret to the traditional 'melt-in-the-mouth' texture is to stir-fry the pork briefly, then let it simmer gently in the sweet soy reduction until the sauce becomes a sticky, glossy glaze."
    },
    "pork-kimchi-jjagleui": {
        "culturalContext": "Jjagleui (Pork and Kimchi Reduction Stew) is the intense, rustic cousin of standard Kimchi Jjigae. Originating from the Chungcheong province, the name mimics the bubbling sound of a thick stew boiling down. It is intentionally cooked with very little water until the broth reduces into a thick, salty, spicy, and intensely concentrated gravy. It is not meant to be eaten like a soup, but rather aggressively mashed into a bowl of white rice or used as a powerful, savory dip for fresh vegetable wraps.",
        "substituteExplanation": "The defining characteristic of Jjagleui is its thick, intense concentration. To achieve this without specialty Korean ingredients, use very little liquid. Sauté any fatty local pork (like bacon or shoulder) with the oldest, most sour store-bought kimchi you can find. To mimic the thick, spicy Korean base, stir in a spoonful of tomato paste, a dash of hot sauce, and soy sauce, letting the starches from added local potatoes boil down and naturally thicken the dark, fiery red gravy to an authentic, rice-coating consistency."
    },
    "bakpo-galbi": {
        "culturalContext": "Bakpo-galbi (Thin-Cut Pork Ribs) highlights a unique Korean butchery style. Also known as 'Saeng-galbi' (raw ribs), the pork ribs are butterflied and scored repeatedly until they lie completely flat in a long, thin sheet, attached to the bone. This incredibly delicate knife work ensures that the meat cooks rapidly and absorbs the smoky flavor of the charcoal grill deeply and evenly. It is a highly prized, specialized cut in Korean BBQ, celebrated for its tender, elastic texture and pure, high-quality pork flavor.",
        "substituteExplanation": "Authentic Bakpo-galbi is famous for its intricate butchery, which is hard to find locally. You can mimic this specialized texture by taking standard, boneless pork shoulder steaks or thick pork chops from your local butcher and aggressively scoring them with a knife in a crosshatch pattern on both sides. Marinate them in a simple mix of local soy sauce, blended apple (for sweetness and tenderizing), and abundant garlic. Grilling these scored steaks over high heat flawlessly recreates the tender, caramelized, authentic Korean BBQ texture."
    },
    "gochujang-bulgogi": {
         "culturalContext": "Gochujang Bulgogi (Spicy Marinated Pork) is the fiery counterpart to the famous sweet soy beef Bulgogi. Originally popularized by working-class citizens seeking cheap, intensely flavorful proteins, it utilizes thinly sliced pork shoulder heavily coated in a sticky, bright red fermented chili paste (Gochujang) marinade. Grilled fast over an open flame, the high sugar content in the chili paste chars, creating an intoxicating, smoky, spicy, and sweet crust. It is the ultimate, aggressive flavor bomb of Korean street food and casual diners.",
        "substituteExplanation": "The heart of this dish is the thick, spicy-sweet glaze. Gochujang is ideal, but a fantastic local hack is blending Sriracha with a spoonful of BBQ sauce, a dash of soy sauce, and local honey or dark brown sugar. This combination perfectly mimics the thick, smoky, and complex sweet-heat of the authentic Korean paste. Marinate ultra-thin slices of cheap local pork shoulder or belly in this mix, and pan-fry on the highest possible heat to achieve that crucial, authentic charred street-food crust."
    },
    "spicy-squid-radish-soup": {
         "culturalContext": "Ojing-eo Muguk (Spicy Squid and Radish Soup) is a staple household soup, celebrated for its incredibly clean, brilliant, and refreshing (Siwonhan) broth. By boiling robust Korean radish (Mu) with fresh squid and a dash of red chili flakes, the soup extracts a profound, sweet oceanic flavor that is intensely comforting. It is notoriously famous in Korea as an elite hangover cure and an effortless winter warmer, demonstrating the Korean culinary philosophy of extracting massive flavor from just two or three high-quality ingredients.",
        "substituteExplanation": "Korean radish (Mu) has a specific sweet density, but standard white Daikon radish or even robust white turnips found in Western supermarkets provide the exact same peppery sweetness when boiled. You don't need Korean chili flakes; a dash of standard paprika for color and a pinch of cayenne for heat works flawlessly. Using locally available frozen or fresh squid rings and boiling them briefly with the root vegetables and a splash of soy sauce yields an extraordinarily authentic, profoundly refreshing, clean seafood broth."
    },
    "cold-cucumber-seaweed-soup": {
         "culturalContext": "Oi Miyeok Naengguk (Cold Cucumber and Seaweed Soup) is Korea's brilliant, icy answer to sweltering, humid summers. It is not a soup in the Western sense, but rather an icy, sweet, intensely tangy, and garlicky chilled broth filled with slippery seaweed and incredibly crisp julienned cucumbers. Served with floating ice cubes alongside heavy, spicy main dishes, it acts as a phenomenal palate cleanser. The sharp vinegar cuts through fat, while the cold, hydrating ingredients instantly lower the body temperature.",
        "substituteExplanation": "This recipe is incredibly easy to replicate with standard ingredients. Any crisp local cucumber (like English or Persian) works perfectly. Standard dried wakame seaweed (widely available in health food aisles) is identical to Korean Miyeok. The icy, refreshing broth requires zero specialty items—it is a simple, precise balancing act of cold water, standard white vinegar, sugar, salt, and minced local garlic. Chilled in the fridge, this simple mixture instantly creates an exact replica of this iconic, thirst-quenching traditional Korean summer dish."
    }
}

import os
recipes_file = r'c:\Users\admin\OneDrive\바탕 화면\안티그래비티 자동화\kfood-platform\src\data\recipes.json'

with open(recipes_file, 'r', encoding='utf-8') as f:
    recipes = json.load(f)

for r in recipes:
    rid = r['id']
    if rid in seo_data:
        r['culturalContext'] = seo_data[rid]['culturalContext']
        r['substituteExplanation'] = seo_data[rid]['substituteExplanation']

with open(recipes_file, 'w', encoding='utf-8') as f:
    json.dump(recipes, f, indent=2, ensure_ascii=False)

print("Successfully added SEO rich content to all recipes.")
